image: docker:latest
services:
  - name: docker:dind
    #command: ["--insecure-registry=$REGISTRY_FQDN", "--tls=false"]
    alias: docker

variables:
  TESTCONTAINERS_HOST_OVERRIDE: "host.docker.internal"
  TESTCONTAINERS_RYUK_DISABLED: "true"
  # Instruct Testcontainers to use the daemon of DinD.
  DOCKER_HOST: "tcp://localhost:2375"
  # Instruct Docker not to start over TLS.
  DOCKER_TLS_CERTDIR: ""
  # Improve performance with overlayfs.
  DOCKER_DRIVER: overlay2

stages:
  - test
  - build
  - package

test:
  image: openjdk:14
  stage: test
  script:
    - ./gradlew test

build:
  image: openjdk:14
  stage: build
  script:
    - ./gradlew bootJar
  artifacts:
    paths:
      - build/libs/pki-ra-acme-server-1.0-SNAPSHOT.jar
    expire_in: 1 week

package:
  stage: package

  before_script:
    - echo "$gitlab-deploy-token" | docker login $REGISTRY_FQDN --username gitlab-deploy-token --password-stdin

  script:
    - docker build -t $REGISTRY_FQDN/win-ra/winllc-ra-acme-server:latest .
    - docker push $REGISTRY_FQDN/win-ra/winllc-ra-acme-server:latest