image: docker:latest
services:
  - name: docker:dind
    command: ["--insecure-registry=registry.gitlab.winllc-dev.com"]

variables:
  TESTCONTAINERS_HOST_OVERRIDE: "host.docker.internal"
  TESTCONTAINERS_RYUK_DISABLED: "true"
  # Instruct Testcontainers to use the daemon of DinD.
  DOCKER_HOST: "tcp://localhost:2375"
  # Instruct Docker not to start over TLS.
  DOCKER_TLS_CERTDIR: ""
  # Improve performance with overlayfs.
  DOCKER_DRIVER: overlay2

stages:
  - test
  - build
  - package

test:
  image: openjdk:14
  stage: test
  script:
    - ./gradlew test

build:
  image: openjdk:14
  stage: build
  script:
    - ./gradlew bootJar
  artifacts:
    paths:
      - build/libs/pki-ra-acme-server-1.0-SNAPSHOT.jar
    expire_in: 1 week

package:
  stage: package
  script:
    - docker build -t registry.gitlab.winllc-dev.com/root/acme-server:latest .
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.gitlab.winllc-dev.com
    - docker push registry.gitlab.winllc-dev.com/root/acme-server:latest