image: docker:latest
services:
  - name: docker:dind
    command: ["--insecure-registry=registry.gitlab.winllc-dev.com"]

variables:
  DOCKER_TLS_CERTDIR: ""
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"
  DOCKER_DRIVER: overlay

stages:
  - build
  - package

build:
  image: gradle:7.1-jdk11
  stage: build
  script:
    - gradle -x test build
  artifacts:
    paths:
      - build/libs/winllc-acme-server-1.0-SNAPSHOT.jar

package:
  stage: package
  script:
    - docker build -t registry.gitlab.winllc-dev.com/root/acme-server .
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.gitlab.winllc-dev.com
    - docker push registry.gitlab.winllc-dev.com/root/acme-server